-- RetiFlux™ — SKU catalog table for PRT form
-- Run in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS skus (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sku text NOT NULL UNIQUE,
  product_name text NOT NULL,
  variant text,
  subdivision text NOT NULL,
  uom text NOT NULL DEFAULT 'KAR',
  shelf_life_days integer,
  sachet_type text,
  tablet_type text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS skus_sku_idx ON skus(sku);
CREATE INDEX IF NOT EXISTS skus_subdivision_idx ON skus(subdivision);
CREATE INDEX IF NOT EXISTS skus_active_idx ON skus(is_active) WHERE is_active = true;

-- RLS: allow anon to read SKUs (form dropdown)
ALTER TABLE skus ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "skus_anon_select" ON skus;
CREATE POLICY "skus_anon_select" ON skus FOR SELECT TO anon USING (is_active = true);

-- Default SKUs (BIDCO Africa) — replaces all existing
DELETE FROM skus;

-- UoMs: KAR=carton, CTN=carton(outer), BTL=bottle, PCS=pieces, KGS=kg, LTR=litre, PKT=packet, JRY=jerry
INSERT INTO skus (sku, product_name, variant, subdivision, uom, shelf_life_days, sachet_type, tablet_type) VALUES
  ('MSAFI-LAV-500-12', 'Msafi Lavender Fresh', '12×500g + 100g Msafi Clear Tablet', 'Detergents', 'KAR', 365, 'M.Lavender Fresh 0.5KG', 'Msafi Clear 100g'),
  ('MSAFI-WHT-500-12', 'Msafi White', '12×500g + 100g Msafi Clear Tablet', 'Detergents', 'KAR', 365, 'M.White 0.5KG', 'Msafi Clear 100g'),
  ('MSAFI-LAV-1KG-6', 'Msafi Lavender Fresh', '6×1KG + 150g Msafi Clear Tablet', 'Detergents', 'KAR', 365, 'M.Lavender Fresh 1KG', 'Msafi Clear 150g'),
  ('MSAFI-WHT-1KG-6', 'Msafi White', '6×1KG + 150g Msafi Clear Tablet', 'Detergents', 'KAR', 365, 'M.White 1KG', 'Msafi Clear 150g'),
  ('ELI-2L-12', 'Elianto Corn Oil', '2 Litre · 12-Pack', 'Oils & Fats', 'KAR', 540, NULL, NULL),
  ('ELI-5L-4', 'Elianto Corn Oil', '5 Litre · 4-Pack', 'Oils & Fats', 'KAR', 540, NULL, NULL),
  ('GFRY-1L-12', 'Golden Fry Vegetable Oil', '1 Litre · 12-Pack', 'Oils & Fats', 'KAR', 540, NULL, NULL),
  ('GFRY-2L-6', 'Golden Fry Vegetable Oil', '2 Litre · 6-Pack', 'Oils & Fats', 'KAR', 540, NULL, NULL),
  ('SGOLD-2L-12', 'Sungold Lite Sunflower Oil', '2 Litre · 12-Pack', 'Oils & Fats', 'KAR', 540, NULL, NULL),
  ('SGOLD-5L-4', 'Sungold Lite Sunflower Oil', '5 Litre · 4-Pack', 'Oils & Fats', 'KAR', 540, NULL, NULL),
  ('BAHARI-2L-12', 'Bahari Fry Vegetable Oil', '2 Litre · 12-Pack', 'Oils & Fats', 'KAR', 540, NULL, NULL),
  ('UFUTA-2L-12', 'Ufuta Pure Cooking Oil', '2 Litre · 12-Pack', 'Oils & Fats', 'KAR', 540, NULL, NULL),
  ('YGOLD-1KG-12', 'Yello Gold Vegetable Fat', '1 KG · 12-Pack', 'Oils & Fats', 'KGS', 365, NULL, NULL),
  ('KIMBO-1KG-12', 'Kimbo Vegetable Fat', '1 KG · 12-Pack', 'Oils & Fats', 'KGS', 365, NULL, NULL),
  ('SOYA-2L-12', 'SoyaGold Cooking Oil', '2 Litre · 12-Pack', 'Oils & Fats', 'LTR', 540, NULL, NULL),
  ('OLIVE-750ML-12', 'Olive Gold Olive Oil', '750ml · 12-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('GENTAL-1KG-12', 'Gental Machine Wash', '1 KG · 12-Pack', 'Detergents', 'KGS', 365, NULL, NULL),
  ('NURU-500ML-24', 'Nuru Dish Wash Liquid', '500ml · 24-Pack', 'Detergents', 'BTL', 365, NULL, NULL),
  ('NURU-1L-12', 'Nuru Dish Wash Liquid', '1 Litre · 12-Pack', 'Detergents', 'BTL', 365, NULL, NULL),
  ('WSTAR-400G-24', 'White Star Washing Bar', '400g · 24-Pack', 'Soaps & Hygiene', 'PCS', 365, NULL, NULL),
  ('GAEA-ALOE-100G-48', 'Gaea Aloe Bathing Soap', '100g · 48-Pack', 'Soaps & Hygiene', 'PCS', 365, NULL, NULL),
  ('MILELE-100G-48', 'Milele Milky Bathing Soap', '100g · 48-Pack', 'Soaps & Hygiene', 'PCS', 365, NULL, NULL),
  ('BIDCO-CRM-400G-24', 'Bidco Cream Laundry Bar', '400g · 24-Pack', 'Soaps & Hygiene', 'PCS', 365, NULL, NULL),
  ('PLANET-500ML-24', 'Planet Aqua Water', '500ml · 24-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('NOODIES-70G-48', 'Noodies Instant Noodles', '70g · 48-Pack', 'Foods', 'PKT', 365, NULL, NULL),
  ('MARI-100G-48', 'Mariandazi Baking Powder', '100g · 48-Pack', 'Foods', 'PKT', 365, NULL, NULL),
  ('GENTAL-HW-500ML-12', 'Gental Care Hand Wash', '500ml · 12-Pack', 'Soaps & Hygiene', 'BTL', 365, NULL, NULL),
  ('GENTAL-FS-1L-6', 'Gental Care Fabric Softener', '1 Litre · 6-Pack', 'Detergents', 'BTL', 365, NULL, NULL),
  ('CHIPO-1KG-12', 'Chipo Vegetable Fat', '1 KG · 12-Pack', 'Oils & Fats', 'KGS', 365, NULL, NULL),
  ('MALLOW-1KG-12', 'Mallo Vegetable Fat', '1 KG · 12-Pack', 'Oils & Fats', 'KGS', 365, NULL, NULL),
  ('ELI-500ML-24', 'Elianto Corn Oil', '500ml · 24-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('ELI-1L-12', 'Elianto Corn Oil', '1 Litre · 12-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('ELI-3L-6', 'Elianto Corn Oil', '3 Litre · 6-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('ELI-10L-4', 'Elianto Corn Oil', '10 Litre · 4-Pack', 'Oils & Fats', 'LTR', 540, NULL, NULL),
  ('ELI-20L-2', 'Elianto Corn Oil', '20 Litre Jerry · 2-Pack', 'Oils & Fats', 'JRY', 540, NULL, NULL),
  ('GFRY-500ML-24', 'Golden Fry Vegetable Oil', '500ml · 24-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('GFRY-3L-6', 'Golden Fry Vegetable Oil', '3 Litre · 6-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('GFRY-5L-4', 'Golden Fry Vegetable Oil', '5 Litre · 4-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('GFRY-10L-4', 'Golden Fry Vegetable Oil', '10 Litre · 4-Pack', 'Oils & Fats', 'LTR', 540, NULL, NULL),
  ('SGOLD-500ML-24', 'Sungold Lite Sunflower Oil', '500ml · 24-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('SGOLD-1L-12', 'Sungold Lite Sunflower Oil', '1 Litre · 12-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('SGOLD-3L-6', 'Sungold Lite Sunflower Oil', '3 Litre · 6-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('SGOLD-10L-4', 'Sungold Lite Sunflower Oil', '10 Litre · 4-Pack', 'Oils & Fats', 'LTR', 540, NULL, NULL),
  ('BAHARI-1L-12', 'Bahari Fry Vegetable Oil', '1 Litre · 12-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('BAHARI-5L-4', 'Bahari Fry Vegetable Oil', '5 Litre · 4-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('UFUTA-1L-12', 'Ufuta Pure Cooking Oil', '1 Litre · 12-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('UFUTA-5L-4', 'Ufuta Pure Cooking Oil', '5 Litre · 4-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('KIMBO-250G-24', 'Kimbo Vegetable Fat', '250g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('KIMBO-500G-24', 'Kimbo Vegetable Fat', '500g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('KIMBO-2KG-6', 'Kimbo Vegetable Fat', '2 KG · 6-Pack', 'Oils & Fats', 'KGS', 365, NULL, NULL),
  ('COWBOY-250G-24', 'Cowboy Cooking Fat', '250g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('COWBOY-500G-24', 'Cowboy Cooking Fat', '500g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('COWBOY-1KG-12', 'Cowboy Cooking Fat', '1 KG · 12-Pack', 'Oils & Fats', 'KGS', 365, NULL, NULL),
  ('COWBOY-2KG-6', 'Cowboy Cooking Fat', '2 KG · 6-Pack', 'Oils & Fats', 'KGS', 365, NULL, NULL),
  ('GBAND-100G-24', 'Gold Band Margarine', '100g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('GBAND-250G-12', 'Gold Band Margarine', '250g · 12-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('GBAND-500G-12', 'Gold Band Margarine', '500g · 12-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('GBAND-1KG-6', 'Gold Band Margarine', '1 KG · 6-Pack', 'Oils & Fats', 'KGS', 365, NULL, NULL),
  ('CHIPSY-250G-24', 'Chipsy Vegetable Fat', '250g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('CHIPSY-500G-24', 'Chipsy Vegetable Fat', '500g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('CHIPSY-1KG-12', 'Chipsy Vegetable Fat', '1 KG · 12-Pack', 'Oils & Fats', 'KGS', 365, NULL, NULL),
  ('CHIPO-250G-24', 'Chipo Vegetable Fat', '250g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('CHIPO-500G-24', 'Chipo Vegetable Fat', '500g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('MALLOW-250G-24', 'Mallo Vegetable Fat', '250g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('MALLOW-500G-24', 'Mallo Vegetable Fat', '500g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('YGOLD-250G-24', 'Yello Gold Vegetable Fat', '250g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('YGOLD-500G-24', 'Yello Gold Vegetable Fat', '500g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('VEEBOL-1KG-12', 'Veebol Vegetable Fat', '1 KG · 12-Pack', 'Oils & Fats', 'KGS', 365, NULL, NULL),
  ('SOYA-1L-12', 'SoyaGold Cooking Oil', '1 Litre · 12-Pack', 'Oils & Fats', 'LTR', 540, NULL, NULL),
  ('SOYA-5L-4', 'SoyaGold Cooking Oil', '5 Litre · 4-Pack', 'Oils & Fats', 'LTR', 540, NULL, NULL),
  ('OLIVE-500ML-12', 'Olive Gold Olive Oil', '500ml · 12-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('OLIVE-1L-6', 'Olive Gold Olive Oil', '1 Litre · 6-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('GAEA-WHT-100G-48', 'Gaea White Bathing Soap', '100g · 48-Pack', 'Soaps & Hygiene', 'PCS', 365, NULL, NULL),
  ('GAEA-LIME-100G-48', 'Gaea Lime Bathing Soap', '100g · 48-Pack', 'Soaps & Hygiene', 'PCS', 365, NULL, NULL),
  ('GAEA-ROSE-100G-48', 'Gaea Rose Bathing Soap', '100g · 48-Pack', 'Soaps & Hygiene', 'PCS', 365, NULL, NULL),
  ('GAEA-ALOE-125G-36', 'Gaea Aloe Bathing Soap', '125g · 36-Pack', 'Soaps & Hygiene', 'PCS', 365, NULL, NULL),
  ('TIGER-400G-24', 'Tiger Washing Bar', '400g · 24-Pack', 'Soaps & Hygiene', 'PCS', 365, NULL, NULL),
  ('WSTAR-200G-48', 'White Star Washing Bar', '200g · 48-Pack', 'Soaps & Hygiene', 'PCS', 365, NULL, NULL),
  ('BIDCO-CRM-200G-48', 'Bidco Cream Laundry Bar', '200g · 48-Pack', 'Soaps & Hygiene', 'PCS', 365, NULL, NULL),
  ('GENTAL-500G-24', 'Gental Machine Wash', '500g · 24-Pack', 'Detergents', 'KGS', 365, NULL, NULL),
  ('GENTAL-2KG-6', 'Gental Machine Wash', '2 KG · 6-Pack', 'Detergents', 'KGS', 365, NULL, NULL),
  ('NURU-250ML-48', 'Nuru Dish Wash Liquid', '250ml · 48-Pack', 'Detergents', 'BTL', 365, NULL, NULL),
  ('NURU-2L-6', 'Nuru Dish Wash Liquid', '2 Litre · 6-Pack', 'Detergents', 'BTL', 365, NULL, NULL),
  ('GENTAL-HW-250ML-24', 'Gental Care Hand Wash', '250ml · 24-Pack', 'Soaps & Hygiene', 'BTL', 365, NULL, NULL),
  ('GENTAL-FS-500ML-12', 'Gental Care Fabric Softener', '500ml · 12-Pack', 'Detergents', 'BTL', 365, NULL, NULL),
  ('GERMONIL-500ML-12', 'Germonil Toilet Cleaner', '500ml · 12-Pack', 'Soaps & Hygiene', 'BTL', 365, NULL, NULL),
  ('PLANET-1.5L-12', 'Planet Aqua Water', '1.5 Litre · 12-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('PLANET-500ML-48', 'Planet Aqua Water', '500ml · 48-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('PLANET-ORNG-500ML-24', 'Planet Soda Orange', '500ml · 24-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('PLANET-TANG-500ML-24', 'Planet Soda Tangawizi', '500ml · 24-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('PLANET-PASS-500ML-24', 'Planet Soda Passion', '500ml · 24-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('PLANET-BERRY-500ML-24', 'Planet Soda Mixed Berries', '500ml · 24-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('SUNQUICK-BC-500ML-12', 'Sunquick Blackcurrant', '500ml · 12-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('SUNQUICK-ORG-500ML-12', 'Sunquick Orange', '500ml · 12-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('SIMBA-250ML-24', 'Simba Energy Drink', '250ml · 24-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('SIMBA-500ML-12', 'Simba Energy Drink', '500ml · 12-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('BUBBLE-500ML-24', 'Bubble Up Soda', '500ml · 24-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('AMCOLA-500ML-24', 'American Cola', '500ml · 24-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('NOODIES-70G-96', 'Noodies Instant Noodles', '70g · 96-Pack', 'Foods', 'PKT', 365, NULL, NULL),
  ('NOODIES-140G-24', 'Noodies Instant Noodles', '140g · 24-Pack', 'Foods', 'PKT', 365, NULL, NULL),
  ('MARI-100G-96', 'Mariandazi Baking Powder', '100g · 96-Pack', 'Foods', 'PKT', 365, NULL, NULL),
  ('MARI-200G-48', 'Mariandazi Baking Powder', '200g · 48-Pack', 'Foods', 'PKT', 365, NULL, NULL),
  ('TAISTI-500G-24', 'Taisti Spaghetti', '500g · 24-Pack', 'Foods', 'PCS', 180, NULL, NULL),
  ('ELBBIN-100G-48', 'Elbbin Nibble Snacks', '100g · 48-Pack', 'Foods', 'PCS', 180, NULL, NULL),
  ('SUNTOP-1L-12', 'Suntop Berries', '1 Litre · 12-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('RIBE-1L-12', 'Ribena', '1 Litre · 12-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('JUO-500ML-24', 'Juo Fruit Drink', '500ml · 24-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('JOZ-500ML-24', 'Jooz Fruit Drink', '500ml · 24-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('PURE-NAT-500G-24', 'Pure and Natural Soap Flakes', '500g · 24-Pack', 'Soaps & Hygiene', 'KGS', 365, NULL, NULL),
  ('LUCZ-250ML-24', 'Lucozade Energy', '250ml · 24-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('LUCZ-500ML-12', 'Lucozade Energy', '500ml · 12-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('JUO-250ML-48', 'Juo Fruit Drink', '250ml · 48-Pack', 'Beverages', 'BTL', 365, NULL, NULL),
  ('MILELE-125G-36', 'Milele Milky Bathing Soap', '125g · 36-Pack', 'Soaps & Hygiene', 'PCS', 365, NULL, NULL),
  ('TIGER-200G-48', 'Tiger Washing Bar', '200g · 48-Pack', 'Soaps & Hygiene', 'PCS', 365, NULL, NULL),
  ('NURU-PASTE-500G-24', 'Nuru Dish Wash Paste', '500g · 24-Pack', 'Detergents', 'KGS', 365, NULL, NULL),
  ('SOYA-500ML-24', 'SoyaGold Cooking Oil', '500ml · 24-Pack', 'Oils & Fats', 'BTL', 540, NULL, NULL),
  ('VEEBOL-500G-24', 'Veebol Vegetable Fat', '500g · 24-Pack', 'Oils & Fats', 'PCS', 365, NULL, NULL),
  ('GBAND-25G-144', 'Gold Band Margarine', '25g Sachet · 144-Pack', 'Oils & Fats', 'CTN', 365, NULL, NULL);
